# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\PC\IDAT\CICLO III\ADSOO\PROYECTO\AutopartesOcampoSoli\UI\frmAdministrador.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(562, 517)
        MainWindow.setMinimumSize(QtCore.QSize(562, 517))
        MainWindow.setMaximumSize(QtCore.QSize(562, 517))
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.829, y1:0.107455, x2:0, y2:1, stop:0.295455 rgba(0, 105, 114, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnReporteVentas = QtWidgets.QPushButton(self.centralwidget)
        self.btnReporteVentas.setGeometry(QtCore.QRect(145, 221, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnReporteVentas.setFont(font)
        self.btnReporteVentas.setStyleSheet("border-radius:5px;\n"
"color:white;\n"
"background-color: rgb(0, 65, 108);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\PC\\IDAT\\CICLO III\\ADSOO\\PROYECTO\\AutopartesOcampoSoli\\UI\\../Img/sales.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReporteVentas.setIcon(icon)
        self.btnReporteVentas.setIconSize(QtCore.QSize(32, 32))
        self.btnReporteVentas.setObjectName("btnReporteVentas")
        self.btnReporteInventario = QtWidgets.QPushButton(self.centralwidget)
        self.btnReporteInventario.setGeometry(QtCore.QRect(130, 140, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.btnReporteInventario.setFont(font)
        self.btnReporteInventario.setStyleSheet("border-radius:5px;\n"
"color:white;\n"
"background-color: rgb(0, 65, 108);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\PC\\IDAT\\CICLO III\\ADSOO\\PROYECTO\\AutopartesOcampoSoli\\UI\\../Img/inventory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReporteInventario.setIcon(icon1)
        self.btnReporteInventario.setIconSize(QtCore.QSize(32, 32))
        self.btnReporteInventario.setObjectName("btnReporteInventario")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(127, 26, 351, 91))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(2, 413, 241, 81))
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("c:\\Users\\PC\\IDAT\\CICLO III\\ADSOO\\PROYECTO\\AutopartesOcampoSoli\\UI\\../Img/LOGO PNG 1.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.btnRegresar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegresar.setGeometry(QtCore.QRect(387, 450, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnRegresar.setFont(font)
        self.btnRegresar.setStyleSheet("border-radius:5px;\n"
"color:white;\n"
"background-color: rgb(0, 65, 108);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\PC\\IDAT\\CICLO III\\ADSOO\\PROYECTO\\AutopartesOcampoSoli\\UI\\../Img/left-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRegresar.setIcon(icon2)
        self.btnRegresar.setIconSize(QtCore.QSize(25, 25))
        self.btnRegresar.setObjectName("btnRegresar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 562, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Administrador"))
        self.btnReporteVentas.setText(_translate("MainWindow", "Reporte Ventas"))
        self.btnReporteInventario.setText(_translate("MainWindow", "Reporte Inventario"))
        self.label_3.setText(_translate("MainWindow", "Administrador"))
        self.btnRegresar.setText(_translate("MainWindow", "Regresar"))
